# Requirement: Traefik is installed with a proxy overlay network

version: '3.8'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.wordpress.rule: "Host(`portainer.example.com`)"
        traefik.http.routers.wordpress.entrypoints: websecure
        traefik.http.routers.wordpress.tls: "true"
        traefik.http.services.wordpress.loadbalancer.server.port: 80
        traefik.http.routers.wordpress.tls.certresolver: leresolver

networks:
  proxy:
    external: true
  agent-network:
    attachable: true
    driver_opts:
      encrypted: 'true'

volumes:
  portainer-data: